Submit reviews responder
ropensci-org/buffy pull request #38
Opened 2021-10-28 09:17 UTC by xuanxu

This PR adds a responder listening to the following command: `submit review <REVIEW-URL> time <REVIEW-HOURS>`
The review URL, duration and date are logged in Airtable. 
The responder can also add or remove labels when the number of reviews equals the number of reviewers.

Re: #9

Here's a screenshot of this responder's docs:
![ROpenSci Submit review](https://user-images.githubusercontent.com/6528/139226420-cf8cbe28-d738-43cc-90fd-d4253d9e109b.png)

2021-11-01 07:13 UTC, maelle commented
@xuanxu Thanks a ton!

Will it work if people mistakenly write "3.5h", "3.5 h", "1hour", "3 hours" etc?

2021-11-01 07:18 UTC, maelle commented
> Note: currently the review_date column in the reviews table is only present in the test Airtable database, it is missing from the production database.

Thanks, now added to the production database.

2021-11-01 07:19 UTC, maelle commented
Also, does the "all reviews" completed depend on the reviewers assigned? (as opposed to an arbitrary number of reviews)

2021-11-01 09:22 UTC, mpadge commented
> Also, does the "all reviews" completed depend on the reviewers assigned? (as opposed to an arbitrary number of reviews)

That is critically important, because there definitely are, and will be, cases with `num_reviewers != 2`.

2021-11-02 09:20 UTC, xuanxu commented
> Will it work if people mistakenly write "3.5h", "3.5 h", "1hour", "3 hours" etc?

Currently it would only accept "3", "3.5", "3,5", with no text after that: "submit review URW time 6.5". 
Should I change it to accept also the [h/hour/hours] part?

2021-11-02 09:24 UTC, xuanxu commented
> Also, does the "all reviews" completed depend on the reviewers assigned?

Yes, the responder queries the airtable API for the reviews of all the assigned reviewers, and if they are all complete (review_url is not empty), then it consider all reviews are in and add the label. It works with any number of reviewers in the list. In the example in the docs there's only two, but could be any other number of reviewers.

2021-11-02 09:38 UTC, maelle commented
Thanks @xuanxu!

> Should I change it to accept also the [h/hour/hours] part?

Yes I think it'd be safer (with or without the space before the h).

2021-11-02 10:15 UTC, xuanxu commented
>> Should I change it to accept also the [h/hour/hours] part?
>
> Yes I think it'd be safer (with or without the space before the h).

@maelle Done!

2021-11-02 10:55 UTC, mpadge requested changes
@xuanxu Is it also possible to add an error at the start of `process_message` if `review_time` is in format `HH:MM`? That may happen, and it should be easy to `regex` that pattern and divert to a `respond("Error: ..."); return` clause, right?

2021-11-02 10:59 UTC, xuanxu commented
@mpadge right now that format is not accepted and the command will be ignored. Once we have an "I dont understand that" responder, this will happen automatically. Do still want a specific error message for this case?

2021-11-02 11:15 UTC, mpadge commented
Only  because i though that would be easy to do, and then useful to have a specific response telling people that their time values aren't properly formatted. Your call, but if it's not too difficult, then yes, please!

2021-11-02 11:39 UTC, maelle commented
I'll wait for @xuanxu's answer before merging and testing this.

2021-11-02 12:37 UTC, xuanxu commented
I've added a simple validation: if the time value includes a colon `:` the response will be an "Invalid time format" comment.

2021-11-02 12:37 UTC, merged

2021-11-02 12:37 UTC, maelle commented
Thank you @xuanxu!!

2021-11-02 12:49 UTC, mpadge commented on app/responders/ropensci/submit_review_responder.rb
> +        respond("Error: Invalid time format")
Great @xuanxu, that's exactly what i was imaging! I think that will be very useful - thank you